GET http://localhost:3000/pets

###

GET http://localhost:3000/pets/1

###

POST http://localhost:3000/pets
content-type: application/json

{
    "id": 1,
    "animal": "Cachorro",
    "name": "Frederico",
    "age": 16,
    "breed": "Poodle",
    "color": "Brown",
    "gender": "Male",
}

###

PUT http://localhost:3000/pets/1

content-type: application/json

{
    "animal": "Cachorro",
    "name": "Frederico",
    "age": 16,
    "breed": "Poodle",
    "color": "Brown",
    "gender": "Male",
}

###

DELETE http://localhost:3000/pets/1